name: Go CI

on:
  push:
    paths:
      - hyperion-go/**
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  #  test:
  #    name: Run tests
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #
  #      - name: Set up Go
  #        uses: actions/setup-go@v4
  #        with:
  #          go-version: 1.23.3
  #
  #      - name: Cache Go modules
  #        uses: actions/cache@v3
  #        with:
  #          path: |
  #            ~/.cache/go-build
  #            ~/go/pkg/mod
  #          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #          restore-keys: |
  #            ${{ runner.os }}-go-
  #
  #      - name: Test
  #        run: go test -v ./...


  fmt:
    defaults:
      run:
        working-directory: hyperion-go
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run go fmt
        run: |
          fmt_output=$(go fmt ./...)
          if [ -n "$fmt_output" ]; then
            echo "Go files need formatting:"
            echo "$fmt_output"
            exit 1
          fi

  build:
    defaults:
      run:
        working-directory: hyperion-go
    name: Build Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

